version: '3.9'

services:
  seq:
    image: datalust/seq
    ports:
      - 5342:80
      - 5341:5341
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

volumes:
  rps_seq_data: